{{- if .Values.graphite.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-metrics.fullname" . }}-graphite-write-proxy
  labels:
    app: {{ template "enterprise-metrics.name" . }}-graphite-write-proxy
    chart: {{ template "enterprise-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.graphite_write_proxy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.graphite_write_proxy.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    app: {{ template "enterprise-metrics.name" . }}-graphite-write-proxy
    release: {{ .Release.Name }}
  {{- end -}}
